# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1480f6f2e668a16a634fb397214e7a9b600c8810496893ceb3be969b5c5ba164a67880f1bfe63eae3f028d73c683cb25d3d844b40704a38bf1f4f16cfb656a32

test:
  secret_key_base: d237411d06afc6f4538abcee62a388b416bbf3a50177b8aab1acfaf3b8706f80bd5f935692a1f6bc46f4b4d80104b1f7904be067e9b1536d5be79943ad95fcd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
