# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5efadab0acb8d909683350db32b86de00593d05f0a9146dca657368e88cb2933770bb6ba632075e63f6cffb41b7a1a8b7d397d057b6b64bb1e92b954c9c633

test:
  secret_key_base: e2d1f4f09916adeb8117022b0c28847f7bdf2e5980573219f7154f2c3f4e20d4da9a85c3965c3de6d5159fad1beb973463ded84e8cbc51136370bbf4ab688870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
